import { NextRequest, NextResponse } from "next/server"
import { createClient as createServiceClient } from "@supabase/supabase-js"

/**
 * DELETE /api/dev/reset-simulation?plan_id=<uuid>
 *
 * Purges all synthetic data generated by /api/dev/simulate-pricing:
 *   - price_point_posteriors WHERE segment_hash LIKE 'sim:%' for this plan's candidates
 *   - paywall_impressions WHERE is_synthetic = true AND account matches
 *
 * Same auth guard as the simulator.
 */
export async function DELETE(request: NextRequest) {
  const simSecret = request.headers.get("x-sim-secret")
  const isAuthorised =
    simSecret === process.env.SIM_SECRET ||
    process.env.NODE_ENV !== "production"

  if (!isAuthorised) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 })
  }

  const plan_id = request.nextUrl.searchParams.get("plan_id")
  if (!plan_id) return NextResponse.json({ error: "plan_id required" }, { status: 400 })

  const service = createServiceClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  )

  // Get all candidate IDs for this plan
  const { data: candidates } = await service
    .from("plan_price_candidates")
    .select("id")
    .eq("plan_id", plan_id)

  const candidateIds = (candidates ?? []).map((c: { id: string }) => c.id)

  let deletedPosteriors = 0
  let deletedImpressions = 0

  // Delete synthetic posteriors (segment_hash LIKE 'sim:%')
  if (candidateIds.length > 0) {
    const { data: syntheticPosts } = await service
      .from("price_point_posteriors")
      .select("price_candidate_id, segment_hash")
      .in("price_candidate_id", candidateIds)
      .like("segment_hash", "sim:%")

    if (syntheticPosts?.length) {
      for (const row of syntheticPosts) {
        await service
          .from("price_point_posteriors")
          .delete()
          .eq("price_candidate_id", row.price_candidate_id)
          .eq("segment_hash", row.segment_hash)
        deletedPosteriors++
      }
    }
  }

  // Delete synthetic paywall_impressions
  // These have is_synthetic = true; filter by plan_id FK (used as fake paywall_id in sim)
  try {
    const { count } = await service
      .from("paywall_impressions")
      .delete({ count: "exact" })
      .eq("paywall_id", plan_id)
      .eq("is_synthetic", true)
    deletedImpressions = count ?? 0
  } catch {
    // is_synthetic column may not exist yet (migration not applied)
  }

  console.log(`[reset-simulation] plan=${plan_id} deleted: ${deletedPosteriors} posteriors, ${deletedImpressions} impressions`)

  return NextResponse.json({
    ok: true,
    plan_id,
    deleted_posteriors: deletedPosteriors,
    deleted_impressions: deletedImpressions,
  })
}
