/**
 * B.3 — Price ladder test.
 * Verifies that every price generated by generatePriceCandidates is exactly
 * on the LADDER_USD scale — no weird decimals like $23.68.
 *
 * Run with:  npx tsx src/lib/__tests__/price-ladder.test.ts
 */

import { LADDER_USD, snapToLadder, generatePriceCandidates, ladderDistance, ladderNeighbours } from "../price-ladder"

const LADDER_CENTS = new Set(LADDER_USD.map(d => d * 100))

let passed = 0, failed = 0

function assert(cond: boolean, msg: string) {
  if (cond) { console.log(`  ✅ ${msg}`); passed++ }
  else       { console.error(`  ❌ ${msg}`); failed++ }
}

// ─── 1. snapToLadder always returns a ladder price ────────────────────────────
console.log("\n─── snapToLadder ───")
const snapTests = [100, 499, 1000, 1234, 2900, 5555, 10000, 29999, 30000]
for (const p of snapTests) {
  const result = snapToLadder(p)
  assert(LADDER_CENTS.has(result), `snap(${p}) = ${result}¢ is on ladder`)
}

// ─── 2. generatePriceCandidates (all aggressiveness levels) ──────────────────
console.log("\n─── generatePriceCandidates ───")
const anchors = [900, 1900, 2900, 4900, 9900]
const levels = ["conservative", "balanced", "aggressive"] as const

for (const anchor of anchors) {
  for (const level of levels) {
    const candidates = generatePriceCandidates(anchor, undefined, undefined, level)
    const allRound = candidates.every(c => LADDER_CENTS.has(c))
    assert(allRound, `${level} anchor=${anchor}¢ → [${candidates.map(c => `$${c/100}`).join(", ")}] all round`)

    // Anchor must always be present (snapped)
    const snappedAnchor = snapToLadder(anchor)
    assert(candidates.includes(snappedAnchor), `  anchor ${snappedAnchor}¢ always included`)

    // balanced + aggressive must always explore; conservative may produce only anchor
    // for ladder positions where ±10% doesn't reach the adjacent rung (e.g. $19)
    const hasBelow = candidates.some(c => c < snappedAnchor)
    const hasAbove = candidates.some(c => c > snappedAnchor)
    if (level !== "conservative") {
      assert(hasBelow || hasAbove, `  has exploration around anchor`)
    }
  }
}

// ─── 3. No non-ladder price ever produced ─────────────────────────────────────
console.log("\n─── Exhaustive round-price check ───")
let totalGenerated = 0
for (const anchor of [500, 700, 900, 1200, 1500, 1900, 2400, 2900, 3900, 4900, 5900, 9900, 19900]) {
  for (const level of levels) {
    const candidates = generatePriceCandidates(anchor, undefined, undefined, level)
    for (const c of candidates) {
      totalGenerated++
      if (!LADDER_CENTS.has(c)) {
        console.error(`  ❌ Non-ladder price generated: ${c}¢ ($${c/100}) at anchor=${anchor} level=${level}`)
        failed++
      }
    }
  }
}
console.log(`  ✅ ${totalGenerated} prices generated — all on ladder`)
passed++

// ─── 4. ladderDistance ───────────────────────────────────────────────────────
// LADDER: [..., 24, 29, 34, 39, ...] → $29=idx7, $34=idx8, $39=idx9, $49=idx11
console.log("\n─── ladderDistance ───")
assert(ladderDistance(2900, 2900) === 0, "$29 → $29 = 0 steps")
assert(ladderDistance(2900, 3400) === 1, "$29 → $34 = 1 step")
assert(ladderDistance(2900, 3900) === 2, "$29 → $39 = 2 steps")
assert(ladderDistance(900,  99900) === 999, "off-ladder → 999")

// ─── 5. ladderNeighbours ─────────────────────────────────────────────────────
// ±1 from $29 (idx7): $24 (idx6) and $34 (idx8)
console.log("\n─── ladderNeighbours ───")
const neighbours29 = ladderNeighbours(2900, 1)
assert(neighbours29.includes(2400), "$29 has $24 as neighbour")
assert(neighbours29.includes(2900), "$29 includes itself")
assert(neighbours29.includes(3400), "$29 has $34 as neighbour")
assert(neighbours29.length === 3,   "$29 has exactly 3 neighbours (±1)")

// ─── Summary ─────────────────────────────────────────────────────────────────
console.log(`\n${"─".repeat(55)}`)
console.log(`Tests passed: ${passed}  failed: ${failed}`)
if (failed > 0) process.exit(1)
